[package]
name = "http"
version = "0.1.0-pre"
authors = [ "Chris Morgan <me@chrismorgan.info>" ]
build = "sh prebuild.sh"

[lib]
name = "http"
path = "src/http/lib.rs"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl.git"

[dependencies.url]
git = "https://github.com/servo/rust-url"
